name:  Writon Nodejs(TypeScript) CI with NPM and CD with Docker & AWS EC2


on:
  push:

    branches: [ "develop" ]


  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
    # 소스코드 다운로드
    - name: Checkout code
      uses: actions/checkout@v3

    - run: npm install
    # ENV SDK 세팅
    - name: Setting env file
      run: |
        touch .env
        echo "${{ secrets.ENVTEST }}" >> .env
      shell: bash

    # FIREBASE SDK 세팅
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "writon-firebase-admin.json"
        json: ${{ secrets.FIREBASE }}

    - name: Build Docker Image For Node.js
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/writon-test:1.0 -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/writon-test:1.0
         
    # 서버에서 Docker 이미지 실행
    - name: EC2 Docker Run
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          docker stop writon-test
          docker rm writon-test
          docker rmi ${{ secrets.DOCKER_USERNAME }}/writon-test:1.0
          docker pull ${{ secrets.DOCKER_USERNAME }}/writon-test:1.0
          docker run -d -p 86:3003 --name writon-test ${{ secrets.DOCKER_USERNAME }}/writon-test:1.0




          






           

        
           